project_name: cloudcat

env:
  - GO111MODULE=on

builds:
  - id: cloudcat
    main: ./cmd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.CommitSHA={{ .ShortCommit }}
    flags:
      - -trimpath
    binary: cloudcat
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
        goarm: 5

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

changelog:
  skip: true